blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/yourusername/currency-converter/blob/main/README.md
    about: Please check the documentation before opening an issue.
  - name: Security Issues
    url: https://github.com/yourusername/currency-converter/blob/main/SECURITY.md
    about: Please report security vulnerabilities according to our security policy.