name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 1' # Run weekly on Mondays
  workflow_dispatch:

jobs:
  dependency-update:
    name: Check and update dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check for updates
        id: ncu
        run: |
          npx npm-check-updates --target minor -u
          git diff package.json
          
      - name: Create pull request if updates exist
        if: steps.ncu.outcome == 'success'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update dependencies'
          title: 'chore(deps): update dependencies'
          body: |
            This PR updates dependencies to their latest minor versions.
            
            Changes are automatically generated by the Dependency Updates workflow.
            
            Please review the changes carefully and run the CI pipeline to verify everything works as expected.
          branch: dependency-updates
          base: develop
          labels: dependencies